### PR TITLE
subdomain: properly check that a DNS zone has no more records inside

### LINKED ISSUE #28: "unauthorized error cannot add subdomain ahmedthabet-wiki-w1 to zone tfgw-testnet-01.3x0.me",
when deploying a wiki I used `w1` i'm sure i used it before somewhere, but wasn't in my workloads list. after continuing with the chatflow it failed node 6RZfnjuXVLFdtZh218hn4BLzsoKkTVpweqWECk5YUKud with workload id 478645

https://explorer.testnet.grid.tf/api/v1/reservations/workloads/478645

the error message was `"unauthorized error cannot add subdomain ahmedthabet-wiki-w1 to zone tfgw-testnet-01.3x0.me",`

I think we can do some more validation on the domain user or even adding extra character or something

### PR DESCRIPTION
**Pull request by zaibon**
fixes #28

### CODE REVIEW

File: dns/dns_zone.go [hunk 1]
```diff
@@ -86,6 +86,15 @@ func (z *Zone) Remove(r Record) {
 
 type records map[RecordType][]Record
 
+func (rs records) IsEmpty() bool {
+	for _, records := range rs {
+		if len(records) > 0 {
+			return true
```
Comment (LeeSmet) [inline dns/dns_zone.go]: s/true/false ?

**Review by LeeSmet — CHANGES_REQUESTED** [review]

File: dns/dns_zone.go (hunk 1 above)
Comment (zaibon) [reply dns/dns_zone.go]: woopsy

**Review by LeeSmet — CHANGES_REQUESTED** [review]
code looks good but tests are failing for some reason
